<a href="https://colab.research.google.com/github/reedhodges/udemy_pytorch_course/blob/main/udemy_course_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#print(torch.__version__)

In [ ]:
!nvidia-smi

Fri Feb 16 16:38:12 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [ ]:
random_tensor = torch.rand(3, 4, 5)
random_tensor

tensor([[[0.7701, 0.8971, 0.3266, 0.3719, 0.4555],
         [0.1589, 0.6005, 0.4678, 0.7590, 0.4213],
         [0.5230, 0.3541, 0.7909, 0.9361, 0.4887],
         [0.4531, 0.0774, 0.2567, 0.1293, 0.9150]],

        [[0.2651, 0.3550, 0.6849, 0.1180, 0.6726],
         [0.7504, 0.3809, 0.3095, 0.6793, 0.2411],
         [0.4114, 0.0865, 0.7763, 0.0851, 0.0142],
         [0.4570, 0.2091, 0.3003, 0.0964, 0.0304]],

        [[0.2160, 0.3587, 0.6995, 0.0058, 0.1728],
         [0.5536, 0.8766, 0.9521, 0.4948, 0.6454],
         [0.9895, 0.4403, 0.5758, 0.6462, 0.0498],
         [0.4991, 0.6133, 0.5694, 0.3354, 0.1049]]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height (pixels), width, color channels (rgb)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
one.dtype

torch.float32

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
like_zeroes = torch.zeros_like(one) # this makes a tensor of zeros of the same shape as the argument
like_zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # datatype
                               device=None, # which device, e.g. cpu or cuda (gpu), the tensor lives on
                               requires_grad=False) # whether or not to track gradients with tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
print(float_16_tensor)
print(f"Datatype of tensor: {float_16_tensor.dtype}")
print(f"Shape of tensor: {float_16_tensor.shape}")
print(f"Device tensor is on: {float_16_tensor.device}")

tensor([3., 6., 9.], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3])
Device tensor is on: cpu


In [ ]:
torch.mul(float_16_tensor,10)

tensor([30., 60., 90.], dtype=torch.float16)

In [ ]:
tensor = torch.tensor([1,2,3])
tensor * tensor # element-wise multiplication

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor,tensor) # matrix multiplication

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

compare runtime of for-loop versus built-in function

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.05 ms, sys: 0 ns, total: 3.05 ms
Wall time: 5.98 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.27 ms, sys: 0 ns, total: 1.27 ms
Wall time: 1.18 ms


tensor(14)

In [ ]:
tensor = torch.rand(2,3)
tensor

tensor([[0.4232, 0.6803, 0.7231],
        [0.4078, 0.5371, 0.1343]])

In [ ]:
tensor.T # transpose

tensor([[0.4232, 0.4078],
        [0.6803, 0.5371],
        [0.7231, 0.1343]])

In [ ]:
torch.mm(tensor,tensor.T)

tensor([[1.1646, 0.6351],
        [0.6351, 0.4729]])

In [ ]:
torch.min(tensor)

tensor(0.1343)

In [ ]:
torch.max(tensor)

tensor(0.7231)

In [ ]:
torch.mean(tensor)

tensor(0.4843)

In [ ]:
x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.mean(x.type(torch.float32)) # mean doesn't work on ints

tensor(4.5000)

In [ ]:
torch.sum(x)

tensor(45)

In [ ]:
x.type(torch.float32).mean() # can also do this

tensor(4.5000)

In [ ]:
x.argmin()  # index for min value

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
x_reshaped = x.reshape(10,1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
z[:,0] = 5
z, x  # since z is a view of x (it shares the same memory), changing z changes x
# view is like reshape, but view keeps the same data.. with reshape you can change the reshaped tensor later without altering the original tensor

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x])
x, x_stacked

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x, x_stacked

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 5.,  5.,  5.,  5.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]))

In [ ]:
y = torch.tensor([[1,2,3,4]])
y, y.shape

(tensor([[1, 2, 3, 4]]), torch.Size([1, 4]))

In [ ]:
y.squeeze(), y.squeeze().shape

(tensor([1, 2, 3, 4]), torch.Size([4]))

In [ ]:
y.shape

torch.Size([1, 4])

In [ ]:
y.unsqueeze(dim=0), y.unsqueeze(dim=0).shape

(tensor([[[1, 2, 3, 4]]]), torch.Size([1, 1, 4]))

In [ ]:
y.unsqueeze(dim=1), y.unsqueeze(dim=1).shape

(tensor([[[1, 2, 3, 4]]]), torch.Size([1, 1, 4]))

In [ ]:
y.unsqueeze(dim=2), y.unsqueeze(dim=2).shape

(tensor([[[1],
          [2],
          [3],
          [4]]]),
 torch.Size([1, 4, 1]))

In [ ]:
x_original = torch.rand(size=(2, 2, 3))
x_permuted = x_original.permute(2, 0, 1)  # this puts the 2nd dimension in 0th place, 0th dimension in 1st place, 1st dimension in 2nd place
# it returns a view so changing the value of x_original changes x_permuted
x_original.shape, x_permuted.shape

(torch.Size([2, 2, 3]), torch.Size([3, 2, 2]))

In [ ]:
x_original, x_permuted

(tensor([[[0.6650, 0.4992, 0.3824],
          [0.0399, 0.1859, 0.1397]],
 
         [[0.9461, 0.7694, 0.1795],
          [0.9589, 0.7014, 0.9629]]]),
 tensor([[[0.6650, 0.0399],
          [0.9461, 0.9589]],
 
         [[0.4992, 0.1859],
          [0.7694, 0.7014]],
 
         [[0.3824, 0.1397],
          [0.1795, 0.9629]]]))

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
x[:,0,2]

tensor([3])

In [ ]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # this creates float64 instead of default float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1
array, tensor # tensor is unchanged

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # creates float32 instead of default float64
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor  # unchanged

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch

rand_tens_A = torch.rand(3, 4)
rand_tens_B = torch.rand(3, 4)
rand_tens_A, rand_tens_B, rand_tens_A == rand_tens_B

(tensor([[0.5651, 0.6211, 0.4648, 0.9074],
         [0.2563, 0.4792, 0.9670, 0.8399],
         [0.0961, 0.4970, 0.7667, 0.9907]]),
 tensor([[0.3164, 0.5279, 0.0115, 0.7846],
         [0.2742, 0.6976, 0.5093, 0.8757],
         [0.1751, 0.4492, 0.6010, 0.1314]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [ ]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_tens_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
rand_tens_D = torch.rand(3, 4)
rand_tens_C, rand_tens_D, rand_tens_C == rand_tens_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [ ]:
!nvidia-smi

Sun Feb 18 13:43:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy() # can't run numpy on gpu
tensor_on_cpu, tensor_on_gpu

(array([1, 2, 3]), tensor([1, 2, 3], device='cuda:0'))